#!/bin/bash

TEST=$(ps aux | egrep 'sh scr' | egrep -v grep | wc -l)

scp=1

if [ $TEST -lt 4 ]; then

  #COMW=$(ps aux | grep 'watch -n 300' | grep -v grep | wc -l)

  #if [ $COMW -lt 1 ]; then

  #  watch watch -n 300 echo "" > nohup.out

  #fi

  while true; do

    sleep 1s

    while true; do

      sleep 1s
      C=$(who | wc -l)
      #echo "$C"

      if [ $C -ne $scp ]; then
        break
      fi
      COMPROBAR=$(ps aux | egrep 'scrcpy' | egrep 'sh' | egrep -v grep | wc -l)

      if [ $COMPROBAR -lt 1 ]; then

        pkill -9 -t $(who | egrep '([0-9]{1,3}\.){3}[0-9]{1,3}' | tail -1 | egrep -o 'pts\/[0-9]')
        nohup sh scrcpy &
        zenity --error --text="Han parado el proceso de scrcpy"

      fi

    done

    while true; do

      if [ $C -gt 5 ]; then

          pkill -9 -t $(who | egrep '([0-9]{1,3}\.){3}[0-9]{1,3}' | tail -1 | egrep -o 'pts\/[0-9]')

      elif [ $C -le 6 ]; then

        break

      fi

    done

    Z=$(ps aux | egrep zenity | egrep -v grep | wc -l)

    if [ $C -lt $scp ]; then

      scp=$(($scp-1))

    else

      if [ $Z -eq 0 ]; then

        scp=$C

        IP=$(who | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | tail -1)

        echo "ssh - $IP - $(date)" >> /home/luis/.h

        #zenity --error --title="Atencion" --text="$IP metido en tu maquina"

        zenity --question --title="Atención" --text "¿Deseas echar a $IP ?"

        ECHAR=$(echo $?)

        if [ $ECHAR = 0 ]; then

          scp=$(($scp-1))

          pkill -9 -t $(who | egrep '([0-9]{1,3}\.){3}[0-9]{1,3}' | tail -1 | egrep -o 'pts\/[0-9]')

          zenity --question --title="Atención" --text "¿Deseas bloquear a $IP ?"

          BLOQUEAR=$(echo $?)

          if [ $BLOQUEAR = 0 ]; then

            cp /etc/hosts.deny .
            echo "sshd: $IP" >> hosts.deny
            mv hosts.deny /etc/hosts.deny

          fi

        fi

      fi

    fi

  done

fi
